### ISSUE TITLE
Agregar campos en la creacion de un satelite

### ISSUE THREAD

**Issue by juansmolano** [nebulae-tpi/ms-client#1]
En el formulario de CRUD de clientes satelites se debe agregar:

Comisiones o cuotas:
- La comision por servicio que se debe pagar al satelite
- El tipo de comision: en sitio (ON_SITE), o pagada virtualmente (VIRTUAL_WALLET)

Configuraciones de oferta:
- Radio de difusion minimo  (por defecto 200 mts) 
- Radio de difusion maximo  (por defecto 1000 mts)

**Comment by javadababadoo** [comment]
Se agregó nueva pestaña en la página de clientes para gestionar la información referente a satelite.
